### ISSUE TITLE
kaniko arguments

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/docker-build-skill#180]
![Screen Shot 2020-12-20 at 9 07 17 PM](https://user-images.githubusercontent.com/1643888/102741530-71eb2500-4307-11eb-8b06-d0d30f1957ed.png)

Tried to use "--context-sub-path /docker/", but got the log error:

`INFO: Error: unknown flag: --context-sub-path /docker/`

I think I needed to use an = between the parameter name and value "--context-sub-path=/docker/".  Is this a requirement for configuring this skill?

**Comment by ddgenome** [comment]
You can either use an `=` between the option and its value or separate them into two separate arguments. Each element of the Kaniko arguments array is passed as a single argument to kaniko, no parsing of the arguments the way a shell like Bash would is done. Since the string `--context-sub-path /docker/` is not a valid argument to kaniko, kaniko is rejecting it.

**Comment by slimslenderslacks** [comment]
I thought it might be a good idea to add the above details to the parameter description.  Your explanation makes perfect sense but I think I could have used a hint about the --param=value format (or needing to separate --param and value on separate lines).
